# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QSpinBox, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(749, 664)
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(10)
        Form.setFont(font)
        self.generatedbutton = QPushButton(Form)
        self.generatedbutton.setObjectName(u"generatedbutton")
        self.generatedbutton.setGeometry(QRect(10, 620, 721, 31))
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 351, 61))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 20, 71, 31))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(180, 20, 81, 31))
        self.vid = QLineEdit(self.groupBox)
        self.vid.setObjectName(u"vid")
        self.vid.setGeometry(QRect(100, 20, 61, 31))
        self.vid.setMaxLength(4)
        self.vid.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.vid.setReadOnly(False)
        self.pid = QLineEdit(self.groupBox)
        self.pid.setObjectName(u"pid")
        self.pid.setGeometry(QRect(250, 20, 61, 31))
        self.pid.setMaxLength(4)
        self.pid.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pid.setReadOnly(False)
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(380, 10, 351, 601))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(21, 30, 131, 31))
        self.spinBox = QSpinBox(self.groupBox_2)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(130, 30, 51, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(5)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 80, 131, 31))
        self.pcs_ms = QCheckBox(self.groupBox_2)
        self.pcs_ms.setObjectName(u"pcs_ms")
        self.pcs_ms.setGeometry(QRect(160, 80, 141, 31))
        self.pcs_sd = QCheckBox(self.groupBox_2)
        self.pcs_sd.setObjectName(u"pcs_sd")
        self.pcs_sd.setGeometry(QRect(160, 110, 141, 31))
        self.pcs_cf = QCheckBox(self.groupBox_2)
        self.pcs_cf.setObjectName(u"pcs_cf")
        self.pcs_cf.setGeometry(QRect(160, 140, 141, 31))
        self.pcs_msd = QCheckBox(self.groupBox_2)
        self.pcs_msd.setObjectName(u"pcs_msd")
        self.pcs_msd.setGeometry(QRect(160, 170, 141, 31))
        self.pcs_m2 = QCheckBox(self.groupBox_2)
        self.pcs_m2.setObjectName(u"pcs_m2")
        self.pcs_m2.setGeometry(QRect(160, 200, 181, 31))
        self.pcs_xd = QCheckBox(self.groupBox_2)
        self.pcs_xd.setObjectName(u"pcs_xd")
        self.pcs_xd.setGeometry(QRect(160, 230, 181, 31))
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(120, 300, 131, 31))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 340, 101, 31))
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.mmc_support = QCheckBox(self.groupBox_2)
        self.mmc_support.setObjectName(u"mmc_support")
        self.mmc_support.setGeometry(QRect(201, 30, 111, 31))
        self.lun0_assignment = QComboBox(self.groupBox_2)
        self.lun0_assignment.addItem("")
        self.lun0_assignment.addItem("")
        self.lun0_assignment.addItem("")
        self.lun0_assignment.addItem("")
        self.lun0_assignment.addItem("")
        self.lun0_assignment.addItem("")
        self.lun0_assignment.addItem("")
        self.lun0_assignment.setObjectName(u"lun0_assignment")
        self.lun0_assignment.setGeometry(QRect(130, 340, 201, 31))
        self.lun1_assignment = QComboBox(self.groupBox_2)
        self.lun1_assignment.addItem("")
        self.lun1_assignment.addItem("")
        self.lun1_assignment.addItem("")
        self.lun1_assignment.addItem("")
        self.lun1_assignment.addItem("")
        self.lun1_assignment.addItem("")
        self.lun1_assignment.addItem("")
        self.lun1_assignment.setObjectName(u"lun1_assignment")
        self.lun1_assignment.setGeometry(QRect(130, 380, 201, 31))
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 380, 101, 31))
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lun2_assignment = QComboBox(self.groupBox_2)
        self.lun2_assignment.addItem("")
        self.lun2_assignment.addItem("")
        self.lun2_assignment.addItem("")
        self.lun2_assignment.addItem("")
        self.lun2_assignment.addItem("")
        self.lun2_assignment.addItem("")
        self.lun2_assignment.addItem("")
        self.lun2_assignment.setObjectName(u"lun2_assignment")
        self.lun2_assignment.setGeometry(QRect(130, 420, 201, 31))
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 420, 101, 31))
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lun3_assignment = QComboBox(self.groupBox_2)
        self.lun3_assignment.addItem("")
        self.lun3_assignment.addItem("")
        self.lun3_assignment.addItem("")
        self.lun3_assignment.addItem("")
        self.lun3_assignment.addItem("")
        self.lun3_assignment.addItem("")
        self.lun3_assignment.addItem("")
        self.lun3_assignment.setObjectName(u"lun3_assignment")
        self.lun3_assignment.setGeometry(QRect(130, 460, 201, 31))
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 460, 101, 31))
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lun4_assignment = QComboBox(self.groupBox_2)
        self.lun4_assignment.addItem("")
        self.lun4_assignment.addItem("")
        self.lun4_assignment.addItem("")
        self.lun4_assignment.addItem("")
        self.lun4_assignment.addItem("")
        self.lun4_assignment.addItem("")
        self.lun4_assignment.addItem("")
        self.lun4_assignment.setObjectName(u"lun4_assignment")
        self.lun4_assignment.setGeometry(QRect(130, 500, 201, 31))
        self.label_18 = QLabel(self.groupBox_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 500, 101, 31))
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lun5_assignment = QComboBox(self.groupBox_2)
        self.lun5_assignment.addItem("")
        self.lun5_assignment.addItem("")
        self.lun5_assignment.addItem("")
        self.lun5_assignment.addItem("")
        self.lun5_assignment.addItem("")
        self.lun5_assignment.addItem("")
        self.lun5_assignment.addItem("")
        self.lun5_assignment.setObjectName(u"lun5_assignment")
        self.lun5_assignment.setGeometry(QRect(130, 540, 201, 31))
        self.label_19 = QLabel(self.groupBox_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 540, 101, 31))
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 280, 331, 2))
        self.label_20.setStyleSheet(u"background-color: rgb(146, 146, 146);")
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 80, 351, 151))
        self.u1u2 = QCheckBox(self.groupBox_3)
        self.u1u2.setObjectName(u"u1u2")
        self.u1u2.setGeometry(QRect(40, 20, 61, 31))
        self.lpm = QCheckBox(self.groupBox_3)
        self.lpm.setObjectName(u"lpm")
        self.lpm.setGeometry(QRect(110, 20, 51, 31))
        self.power_saving_mode = QCheckBox(self.groupBox_3)
        self.power_saving_mode.setObjectName(u"power_saving_mode")
        self.power_saving_mode.setGeometry(QRect(170, 50, 151, 31))
        self.remote_wakeup = QCheckBox(self.groupBox_3)
        self.remote_wakeup.setObjectName(u"remote_wakeup")
        self.remote_wakeup.setGeometry(QRect(40, 50, 131, 31))
        self.ssc = QCheckBox(self.groupBox_3)
        self.ssc.setObjectName(u"ssc")
        self.ssc.setGeometry(QRect(230, 20, 51, 31))
        self.ltm = QCheckBox(self.groupBox_3)
        self.ltm.setObjectName(u"ltm")
        self.ltm.setGeometry(QRect(170, 20, 51, 31))
        self.readonly = QCheckBox(self.groupBox_3)
        self.readonly.setObjectName(u"readonly")
        self.readonly.setGeometry(QRect(40, 80, 91, 31))
        self.customized_string = QCheckBox(self.groupBox_3)
        self.customized_string.setObjectName(u"customized_string")
        self.customized_string.setGeometry(QRect(170, 80, 141, 31))
        self.label_21 = QLabel(self.groupBox_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(60, 110, 121, 31))
        self.usb_power_setting = QSpinBox(self.groupBox_3)
        self.usb_power_setting.setObjectName(u"usb_power_setting")
        self.usb_power_setting.setGeometry(QRect(180, 110, 71, 31))
        self.usb_power_setting.setMinimum(500)
        self.usb_power_setting.setMaximum(900)
        self.label_22 = QLabel(self.groupBox_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(260, 110, 31, 31))
        self.groupBox_4 = QGroupBox(Form)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 420, 351, 191))
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 20, 101, 31))
        self.v_str = QLineEdit(self.groupBox_4)
        self.v_str.setObjectName(u"v_str")
        self.v_str.setGeometry(QRect(140, 20, 181, 31))
        self.v_str.setMaxLength(8)
        self.v_str.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.v_str.setReadOnly(False)
        self.p_str = QLineEdit(self.groupBox_4)
        self.p_str.setObjectName(u"p_str")
        self.p_str.setGeometry(QRect(140, 60, 181, 31))
        self.p_str.setMaxLength(12)
        self.p_str.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.p_str.setReadOnly(False)
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 60, 101, 31))
        self.s_str = QLineEdit(self.groupBox_4)
        self.s_str.setObjectName(u"s_str")
        self.s_str.setGeometry(QRect(140, 100, 181, 31))
        self.s_str.setMaxLength(10)
        self.s_str.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.s_str.setReadOnly(False)
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 100, 101, 31))
        self.label_12 = QLabel(self.groupBox_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 140, 71, 31))
        self.c_str_0 = QLineEdit(self.groupBox_4)
        self.c_str_0.setObjectName(u"c_str_0")
        self.c_str_0.setGeometry(QRect(140, 140, 41, 31))
        self.c_str_0.setMaxLength(4)
        self.c_str_0.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.c_str_0.setReadOnly(False)
        self.c_str_1 = QLineEdit(self.groupBox_4)
        self.c_str_1.setObjectName(u"c_str_1")
        self.c_str_1.setGeometry(QRect(190, 140, 41, 31))
        self.c_str_1.setMaxLength(4)
        self.c_str_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.c_str_1.setReadOnly(False)
        self.c_str_3 = QLineEdit(self.groupBox_4)
        self.c_str_3.setObjectName(u"c_str_3")
        self.c_str_3.setGeometry(QRect(290, 140, 41, 31))
        self.c_str_3.setMaxLength(4)
        self.c_str_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.c_str_3.setReadOnly(False)
        self.c_str_2 = QLineEdit(self.groupBox_4)
        self.c_str_2.setObjectName(u"c_str_2")
        self.c_str_2.setGeometry(QRect(240, 140, 41, 31))
        self.c_str_2.setMaxLength(4)
        self.c_str_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.c_str_2.setReadOnly(False)
        self.groupBox_5 = QGroupBox(Form)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 240, 351, 171))
        self.label_5 = QLabel(self.groupBox_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 20, 81, 31))
        self.led_mode = QComboBox(self.groupBox_5)
        self.led_mode.addItem("")
        self.led_mode.addItem("")
        self.led_mode.setObjectName(u"led_mode")
        self.led_mode.setGeometry(QRect(110, 20, 201, 31))
        self.groupBox_6 = QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(20, 60, 311, 91))
        self.label_6 = QLabel(self.groupBox_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 20, 81, 31))
        self._3233_pin_defined = QComboBox(self.groupBox_6)
        self._3233_pin_defined.addItem("")
        self._3233_pin_defined.addItem("")
        self._3233_pin_defined.setObjectName(u"_3233_pin_defined")
        self._3233_pin_defined.setGeometry(QRect(90, 20, 201, 31))
        self.sd2_wp_enabled = QCheckBox(self.groupBox_6)
        self.sd2_wp_enabled.setObjectName(u"sd2_wp_enabled")
        self.sd2_wp_enabled.setGeometry(QRect(70, 60, 171, 21))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Genesys Reader EEP Generated Tool", None))
        self.generatedbutton.setText(QCoreApplication.translate("Form", u"Generated EEP File", None))
        self.groupBox.setTitle(QCoreApplication.translate("Form", u"USB VID/PID Setting:", None))
        self.label.setText(QCoreApplication.translate("Form", u"Vendor ID:", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Product ID:", None))
        self.vid.setText(QCoreApplication.translate("Form", u"05E3", None))
        self.pid.setText(QCoreApplication.translate("Form", u"0748", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Form", u"Lun/Icon Setting:", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Lun Number Disp.", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Physical Card Support:", None))
        self.pcs_ms.setText(QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.pcs_sd.setText(QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.pcs_cf.setText(QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.pcs_msd.setText(QCoreApplication.translate("Form", u"microSD", None))
        self.pcs_m2.setText(QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.pcs_xd.setText(QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"Lun Assignment:", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"LUN0 (Icon 0):", None))
        self.mmc_support.setText(QCoreApplication.translate("Form", u"MMC support", None))
        self.lun0_assignment.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.lun0_assignment.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.lun0_assignment.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.lun0_assignment.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.lun0_assignment.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.lun0_assignment.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.lun0_assignment.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.lun1_assignment.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.lun1_assignment.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.lun1_assignment.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.lun1_assignment.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.lun1_assignment.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.lun1_assignment.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.lun1_assignment.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.label_15.setText(QCoreApplication.translate("Form", u"LUN1 (Icon 1):", None))
        self.lun2_assignment.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.lun2_assignment.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.lun2_assignment.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.lun2_assignment.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.lun2_assignment.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.lun2_assignment.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.lun2_assignment.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.label_16.setText(QCoreApplication.translate("Form", u"LUN2 (Icon 2):", None))
        self.lun3_assignment.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.lun3_assignment.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.lun3_assignment.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.lun3_assignment.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.lun3_assignment.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.lun3_assignment.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.lun3_assignment.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.label_17.setText(QCoreApplication.translate("Form", u"LUN3 (Icon 3):", None))
        self.lun4_assignment.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.lun4_assignment.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.lun4_assignment.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.lun4_assignment.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.lun4_assignment.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.lun4_assignment.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.lun4_assignment.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.label_18.setText(QCoreApplication.translate("Form", u"LUN4 (Icon 4):", None))
        self.lun5_assignment.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.lun5_assignment.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.lun5_assignment.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.lun5_assignment.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.lun5_assignment.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.lun5_assignment.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.lun5_assignment.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.label_19.setText(QCoreApplication.translate("Form", u"LUN5 (Icon 5):", None))
        self.label_20.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("Form", u"Hardware Setting:", None))
        self.u1u2.setText(QCoreApplication.translate("Form", u"U1/U2", None))
        self.lpm.setText(QCoreApplication.translate("Form", u"LPM", None))
        self.power_saving_mode.setText(QCoreApplication.translate("Form", u"Power-Saving Mode", None))
        self.remote_wakeup.setText(QCoreApplication.translate("Form", u"Remote WakeUp", None))
        self.ssc.setText(QCoreApplication.translate("Form", u"SSC", None))
        self.ltm.setText(QCoreApplication.translate("Form", u"LTM", None))
        self.readonly.setText(QCoreApplication.translate("Form", u"Read-Only", None))
        self.customized_string.setText(QCoreApplication.translate("Form", u"Customized String", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"USB Power Setting:", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"mA", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Form", u"Customized String Setting:", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Vendor String:", None))
        self.v_str.setText(QCoreApplication.translate("Form", u"Genesys", None))
        self.p_str.setText(QCoreApplication.translate("Form", u"Generic USB", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Product String:", None))
        self.s_str.setText(QCoreApplication.translate("Form", u"0000000000", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Serial String:", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Card String:", None))
        self.c_str_0.setText("")
        self.c_str_1.setText("")
        self.c_str_3.setText("")
        self.c_str_2.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("Form", u"LED Setting:", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"LED Mode:", None))
        self.led_mode.setItemText(0, QCoreApplication.translate("Form", u"Access LED is Card Access", None))
        self.led_mode.setItemText(1, QCoreApplication.translate("Form", u"Access LED is Power Access", None))

        self.groupBox_6.setTitle(QCoreApplication.translate("Form", u"LED GPIO Setting For GL3223 Only:", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Pin Defined:", None))
        self._3233_pin_defined.setItemText(0, QCoreApplication.translate("Form", u"#48: SS Act; #128: HS Act", None))
        self._3233_pin_defined.setItemText(1, QCoreApplication.translate("Form", u"#48: LED Mode; #128: Power", None))

        self.sd2_wp_enabled.setText(QCoreApplication.translate("Form", u"Enable #128 as SD2_WP", None))
    # retranslateUi

