# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QSpinBox, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(749, 664)
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(10)
        Form.setFont(font)
        self.generatedbutton = QPushButton(Form)
        self.generatedbutton.setObjectName(u"generatedbutton")
        self.generatedbutton.setGeometry(QRect(10, 620, 721, 31))
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 351, 61))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 20, 71, 31))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(180, 20, 81, 31))
        self.vid = QLineEdit(self.groupBox)
        self.vid.setObjectName(u"vid")
        self.vid.setGeometry(QRect(100, 20, 61, 31))
        self.vid.setMaxLength(4)
        self.vid.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.vid.setReadOnly(False)
        self.pid = QLineEdit(self.groupBox)
        self.pid.setObjectName(u"pid")
        self.pid.setGeometry(QRect(250, 20, 61, 31))
        self.pid.setMaxLength(4)
        self.pid.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pid.setReadOnly(False)
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(380, 10, 351, 601))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(21, 30, 131, 31))
        self.spinBox = QSpinBox(self.groupBox_2)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(130, 30, 51, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(5)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 80, 131, 31))
        self.checkBox_10 = QCheckBox(self.groupBox_2)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(160, 80, 141, 31))
        self.checkBox_11 = QCheckBox(self.groupBox_2)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setGeometry(QRect(160, 110, 141, 31))
        self.checkBox_12 = QCheckBox(self.groupBox_2)
        self.checkBox_12.setObjectName(u"checkBox_12")
        self.checkBox_12.setGeometry(QRect(160, 140, 141, 31))
        self.checkBox_13 = QCheckBox(self.groupBox_2)
        self.checkBox_13.setObjectName(u"checkBox_13")
        self.checkBox_13.setGeometry(QRect(160, 170, 141, 31))
        self.checkBox_14 = QCheckBox(self.groupBox_2)
        self.checkBox_14.setObjectName(u"checkBox_14")
        self.checkBox_14.setGeometry(QRect(160, 200, 181, 31))
        self.checkBox_15 = QCheckBox(self.groupBox_2)
        self.checkBox_15.setObjectName(u"checkBox_15")
        self.checkBox_15.setGeometry(QRect(160, 230, 181, 31))
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(120, 300, 131, 31))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 340, 101, 31))
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.checkBox_16 = QCheckBox(self.groupBox_2)
        self.checkBox_16.setObjectName(u"checkBox_16")
        self.checkBox_16.setGeometry(QRect(201, 30, 111, 31))
        self.comboBox_3 = QComboBox(self.groupBox_2)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(130, 340, 201, 31))
        self.comboBox_4 = QComboBox(self.groupBox_2)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(130, 380, 201, 31))
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 380, 101, 31))
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBox_5 = QComboBox(self.groupBox_2)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(130, 420, 201, 31))
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 420, 101, 31))
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBox_6 = QComboBox(self.groupBox_2)
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.comboBox_6.setGeometry(QRect(130, 460, 201, 31))
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 460, 101, 31))
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBox_7 = QComboBox(self.groupBox_2)
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.comboBox_7.setGeometry(QRect(130, 500, 201, 31))
        self.label_18 = QLabel(self.groupBox_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 500, 101, 31))
        self.label_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.comboBox_8 = QComboBox(self.groupBox_2)
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.setObjectName(u"comboBox_8")
        self.comboBox_8.setGeometry(QRect(130, 540, 201, 31))
        self.label_19 = QLabel(self.groupBox_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 540, 101, 31))
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 280, 331, 2))
        self.label_20.setStyleSheet(u"background-color: rgb(146, 146, 146);")
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 80, 351, 151))
        self.checkBox = QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(40, 20, 61, 31))
        self.checkBox_2 = QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(110, 20, 51, 31))
        self.checkBox_3 = QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(170, 50, 151, 31))
        self.checkBox_4 = QCheckBox(self.groupBox_3)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(40, 50, 131, 31))
        self.checkBox_5 = QCheckBox(self.groupBox_3)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(230, 20, 51, 31))
        self.checkBox_6 = QCheckBox(self.groupBox_3)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(170, 20, 51, 31))
        self.checkBox_7 = QCheckBox(self.groupBox_3)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(40, 80, 91, 31))
        self.checkBox_9 = QCheckBox(self.groupBox_3)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(170, 80, 141, 31))
        self.label_21 = QLabel(self.groupBox_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(60, 110, 121, 31))
        self.spinBox_2 = QSpinBox(self.groupBox_3)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(180, 110, 71, 31))
        self.spinBox_2.setMinimum(500)
        self.spinBox_2.setMaximum(900)
        self.label_22 = QLabel(self.groupBox_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(260, 110, 31, 31))
        self.groupBox_4 = QGroupBox(Form)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 420, 351, 191))
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 20, 101, 31))
        self.lineEdit_9 = QLineEdit(self.groupBox_4)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(140, 20, 181, 31))
        self.lineEdit_9.setMaxLength(8)
        self.lineEdit_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_9.setReadOnly(False)
        self.lineEdit_10 = QLineEdit(self.groupBox_4)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(140, 60, 181, 31))
        self.lineEdit_10.setMaxLength(12)
        self.lineEdit_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_10.setReadOnly(False)
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 60, 101, 31))
        self.lineEdit_11 = QLineEdit(self.groupBox_4)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(140, 100, 181, 31))
        self.lineEdit_11.setMaxLength(10)
        self.lineEdit_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_11.setReadOnly(False)
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 100, 101, 31))
        self.label_12 = QLabel(self.groupBox_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 140, 71, 31))
        self.lineEdit_12 = QLineEdit(self.groupBox_4)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(140, 140, 41, 31))
        self.lineEdit_12.setMaxLength(4)
        self.lineEdit_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_12.setReadOnly(False)
        self.lineEdit_13 = QLineEdit(self.groupBox_4)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(190, 140, 41, 31))
        self.lineEdit_13.setMaxLength(4)
        self.lineEdit_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_13.setReadOnly(False)
        self.lineEdit_14 = QLineEdit(self.groupBox_4)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(290, 140, 41, 31))
        self.lineEdit_14.setMaxLength(4)
        self.lineEdit_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_14.setReadOnly(False)
        self.lineEdit_15 = QLineEdit(self.groupBox_4)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(240, 140, 41, 31))
        self.lineEdit_15.setMaxLength(4)
        self.lineEdit_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_15.setReadOnly(False)
        self.groupBox_5 = QGroupBox(Form)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 240, 351, 171))
        self.label_5 = QLabel(self.groupBox_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 20, 81, 31))
        self.comboBox = QComboBox(self.groupBox_5)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(110, 20, 201, 31))
        self.groupBox_6 = QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(20, 60, 311, 91))
        self.label_6 = QLabel(self.groupBox_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 20, 81, 31))
        self.comboBox_2 = QComboBox(self.groupBox_6)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(90, 20, 201, 31))
        self.checkBox_8 = QCheckBox(self.groupBox_6)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(70, 60, 171, 21))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Genesys Reader EEP Generated Tool", None))
        self.generatedbutton.setText(QCoreApplication.translate("Form", u"Generated EEP File", None))
        self.groupBox.setTitle(QCoreApplication.translate("Form", u"USB VID/PID Setting:", None))
        self.label.setText(QCoreApplication.translate("Form", u"Vendor ID:", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Product ID:", None))
        self.vid.setText(QCoreApplication.translate("Form", u"05E3", None))
        self.pid.setText(QCoreApplication.translate("Form", u"0748", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Form", u"Lun/Icon Setting:", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Lun Number Disp.", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Physical Card Support:", None))
        self.checkBox_10.setText(QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.checkBox_11.setText(QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.checkBox_12.setText(QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.checkBox_13.setText(QCoreApplication.translate("Form", u"microSD", None))
        self.checkBox_14.setText(QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.checkBox_15.setText(QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"Lun Assignment:", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"LUN0 (Icon 0):", None))
        self.checkBox_16.setText(QCoreApplication.translate("Form", u"MMC support", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.comboBox_3.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.comboBox_3.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.comboBox_4.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.comboBox_4.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.comboBox_4.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.comboBox_4.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.comboBox_4.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.label_15.setText(QCoreApplication.translate("Form", u"LUN1 (Icon 1):", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.comboBox_5.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.comboBox_5.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.comboBox_5.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.comboBox_5.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.label_16.setText(QCoreApplication.translate("Form", u"LUN2 (Icon 2):", None))
        self.comboBox_6.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.comboBox_6.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.comboBox_6.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.comboBox_6.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.comboBox_6.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.comboBox_6.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.comboBox_6.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.label_17.setText(QCoreApplication.translate("Form", u"LUN3 (Icon 3):", None))
        self.comboBox_7.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.comboBox_7.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.comboBox_7.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.comboBox_7.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.comboBox_7.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.comboBox_7.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.comboBox_7.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.label_18.setText(QCoreApplication.translate("Form", u"LUN4 (Icon 4):", None))
        self.comboBox_8.setItemText(0, QCoreApplication.translate("Form", u"MS (Memory Stick)", None))
        self.comboBox_8.setItemText(1, QCoreApplication.translate("Form", u"SD / MMC / EMMC", None))
        self.comboBox_8.setItemText(2, QCoreApplication.translate("Form", u"CF (Compact Flash)", None))
        self.comboBox_8.setItemText(3, QCoreApplication.translate("Form", u"microSD", None))
        self.comboBox_8.setItemText(4, QCoreApplication.translate("Form", u"M2 (Memory Stick Micro)", None))
        self.comboBox_8.setItemText(5, QCoreApplication.translate("Form", u"xD (Extreme Digital)", None))
        self.comboBox_8.setItemText(6, QCoreApplication.translate("Form", u"None", None))

        self.label_19.setText(QCoreApplication.translate("Form", u"LUN5 (Icon 5):", None))
        self.label_20.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("Form", u"Hardware Setting:", None))
        self.checkBox.setText(QCoreApplication.translate("Form", u"U1/U2", None))
        self.checkBox_2.setText(QCoreApplication.translate("Form", u"LPM", None))
        self.checkBox_3.setText(QCoreApplication.translate("Form", u"Power-Saving Mode", None))
        self.checkBox_4.setText(QCoreApplication.translate("Form", u"Remote WakeUp", None))
        self.checkBox_5.setText(QCoreApplication.translate("Form", u"SSC", None))
        self.checkBox_6.setText(QCoreApplication.translate("Form", u"LTM", None))
        self.checkBox_7.setText(QCoreApplication.translate("Form", u"Read-Only", None))
        self.checkBox_9.setText(QCoreApplication.translate("Form", u"Customzed String", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"USB Power Setting:", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"mA", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Form", u"Customized String Setting:", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Vendor String:", None))
        self.lineEdit_9.setText(QCoreApplication.translate("Form", u"Genesys", None))
        self.lineEdit_10.setText(QCoreApplication.translate("Form", u"Generic USB", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Product String:", None))
        self.lineEdit_11.setText(QCoreApplication.translate("Form", u"0000000000", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Serial String:", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Card String:", None))
        self.lineEdit_12.setText("")
        self.lineEdit_13.setText("")
        self.lineEdit_14.setText("")
        self.lineEdit_15.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("Form", u"LED Setting:", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"LED Mode:", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Form", u"Access LED is Card Access", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Form", u"Access LED is Power Access", None))

        self.groupBox_6.setTitle(QCoreApplication.translate("Form", u"LED GPIO Setting For GL3223 Only:", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Pin Defined:", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("Form", u"#48: SS Act; #128: HS Act", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("Form", u"#48: LED Mode; #128: Power", None))

        self.checkBox_8.setText(QCoreApplication.translate("Form", u"Enable #128 as SD2_WP", None))
    # retranslateUi

